#pragma once

#if defined(XFORMERS_USE_CUDA)
#define XFORMERS_HAS_CUDA_BACKEND 1
#else
#define XFORMERS_HAS_CUDA_BACKEND 0
#endif

#if defined(XFORMERS_USE_ROCM)
#define XFORMERS_HAS_ROCM_BACKEND 1
#else
#define XFORMERS_HAS_ROCM_BACKEND 0
#endif

#if defined(XFORMERS_USE_VULKAN)
#define XFORMERS_HAS_VULKAN_BACKEND 1
#else
#define XFORMERS_HAS_VULKAN_BACKEND 0
#endif

#if defined(XFORMERS_USE_OPENCL)
#define XFORMERS_HAS_OPENCL_BACKEND 1
#else
#define XFORMERS_HAS_OPENCL_BACKEND 0
#endif

#if defined(XFORMERS_USE_OPENVINO)
#define XFORMERS_HAS_OPENVINO_BACKEND 1
#else
#define XFORMERS_HAS_OPENVINO_BACKEND 0
#endif

#if defined(XFORMERS_USE_IPEX)
#define XFORMERS_HAS_IPEX_BACKEND 1
#else
#define XFORMERS_HAS_IPEX_BACKEND 0
#endif

#if defined(XFORMERS_USE_OPENGL)
#define XFORMERS_HAS_OPENGL_BACKEND 1
#else
#define XFORMERS_HAS_OPENGL_BACKEND 0
#endif

#define XFORMERS_HAS_GPU_KERNEL_BACKEND \
  (XFORMERS_HAS_CUDA_BACKEND || XFORMERS_HAS_ROCM_BACKEND)
